service: dynamickkk

provider:
  name: aws
  runtime: nodejs12.x
  region: us-east-1

functions:
  create:
    handler: controllers/create.handler
    events:
      - http:
          path: create/
          method: post
          cors: true
  list:
    handler: controllers/list.all
    events:
      - http:
          path: list/
          method: get
          cors: true
  listone:
    handler: controllers/list.one
    events:
      - http:
          path: list/{name}
          method: get
          cors: true
          request:
            parameters:
              paths:
                name: true
  delete:
    handler: controllers/delete.handler
    events:
      - http:
          path: delete/{id}
          method: delete
          cors: true
          request:
            parameters:
              paths:
                id: true
  update:
    handler: controllers/update.handler
    events:
      - http:
          path: update/{id}
          method: put
          cors: true
          request:
            parameters:
              paths:
                id: true
plugins:
  - serverless-offline
